"""Simple deep agent with model configuration from config file.

Model Configuration Priority:
1. model_config.json (from frontend Settings UI) - highest priority
2. Environment variables (OPENAI_API_KEY, OPENAI_MODEL, etc.)
3. Default fallback (Google Gemini)

Hot Reload: In dev mode, LangGraph's watchfiles will automatically reload
when model_config.json is modified by the frontend.

Model Override Support:
- Primary Model: Used for main chat
- Subagents (including general-purpose): Can use different models via model_overrides
- Summarization: Inherits from Primary Model (deepagents library limitation)
- Suggestions: Handled by frontend directly
"""

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from langchain.chat_models import init_chat_model
from langchain_core.language_models import BaseChatModel
from langchain_openai import ChatOpenAI

# Try to import AWS Bedrock support
try:
    from langchain_aws import ChatBedrock
    HAS_BEDROCK = True
except ImportError:
    HAS_BEDROCK = False
    ChatBedrock = None

from deepagents import create_deep_agent
from deepagents.middleware.subagents import DEFAULT_SUBAGENT_PROMPT

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Config file path (same directory as agent.py)
CONFIG_FILE = Path(__file__).parent / "model_config.json"


def load_config_file() -> dict[str, Any] | None:
    """Load model configuration from JSON file.
    
    Returns:
        Configuration dict if file exists and is valid, None otherwise.
    """
    if not CONFIG_FILE.exists():
        logger.info(f"[MODEL CONFIG] Config file not found: {CONFIG_FILE}")
        return None
    
    try:
        with open(CONFIG_FILE, "r") as f:
            config = json.load(f)
        
        # Validate required fields
        if not config.get("provider") or not config.get("model"):
            logger.warning("[MODEL CONFIG] Config file missing provider or model")
            return None
        
        provider = config.get("provider")
        
        # Check credentials based on provider (config file only, no env var fallback)
        if provider == "bedrock":
            # AWS Bedrock uses access key + secret key
            if not config.get("aws_access_key_id") or not config.get("aws_secret_access_key"):
                logger.warning("[MODEL CONFIG] AWS credentials not found in config file for Bedrock")
                return None
        elif provider == "azure":
            # Azure uses endpoint + api key
            if not config.get("azure_api_key") or not config.get("azure_base_url"):
                logger.warning("[MODEL CONFIG] Azure credentials not found in config file")
                return None
        else:
            # Standard API key check for other providers
            if not config.get("api_key"):
                logger.warning("[MODEL CONFIG] No API key found in config file")
                return None
        
        logger.info(f"[MODEL CONFIG] Loaded config from file: provider={provider}, model={config.get('model')}")
        return config
        
    except json.JSONDecodeError as e:
        logger.error(f"[MODEL CONFIG] Invalid JSON in config file: {e}")
        return None
    except Exception as e:
        logger.error(f"[MODEL CONFIG] Error reading config file: {e}")
        return None


def save_config_file(config: dict[str, Any]) -> bool:
    """Save model configuration to JSON file.
    
    This function is called by the frontend API to persist settings.
    
    Args:
        config: Configuration dict with provider, model, api_key, etc.
    
    Returns:
        True if saved successfully, False otherwise.
    """
    try:
        config["_last_updated"] = datetime.now().isoformat()
        config["_comment"] = "This file is auto-generated by the frontend. Edit via Settings UI."
        
        with open(CONFIG_FILE, "w") as f:
            json.dump(config, f, indent=2)
        
        logger.info(f"[MODEL CONFIG] Saved config to file: {CONFIG_FILE}")
        return True
        
    except Exception as e:
        logger.error(f"[MODEL CONFIG] Error saving config file: {e}")
        return False


def create_model_from_params(
    provider: str,
    model_name: str,
    api_key: str | None = None,
    base_url: str | None = None,
    label: str = "",
    # AWS Bedrock specific
    aws_access_key_id: str | None = None,
    aws_secret_access_key: str | None = None,
    aws_region: str | None = None,
    aws_account_id: str | None = None,
    # Azure specific
    azure_base_url: str | None = None,
    azure_api_key: str | None = None,
) -> BaseChatModel | None:
    """Create a model instance from parameters.
    
    Args:
        provider: Provider name (openai, anthropic, google, openrouter, bedrock, azure)
        model_name: Model name/ID
        api_key: API key (optional, falls back to env vars)
        base_url: Base URL for OpenAI-compatible APIs
        label: Label for logging (e.g., "Primary", "Subagent")
        aws_access_key_id: AWS Access Key ID for Bedrock
        aws_secret_access_key: AWS Secret Access Key for Bedrock
        aws_region: AWS Region for Bedrock
        aws_account_id: AWS Account ID for building Inference Profile ARN
        azure_base_url: Azure OpenAI base URL
        azure_api_key: Azure OpenAI API key
    
    Returns:
        Configured model instance, or None if creation fails.
    
    NOTE: All credentials must be provided via parameters (from model_config.json).
    Environment variables are NOT used as fallback for security.
    """
    log_prefix = f"[MODEL CONFIG] [{label}]" if label else "[MODEL CONFIG]"
    
    try:
        if provider == "openai":
            if api_key:
                logger.info(f"{log_prefix} Creating OpenAI model: {model_name}")
                return ChatOpenAI(model=model_name, openai_api_key=api_key)
            else:
                logger.warning(f"{log_prefix} OpenAI API key not configured in Settings")
        
        elif provider == "anthropic":
            if api_key:
                logger.info(f"{log_prefix} Creating Anthropic model: {model_name}")
                return init_chat_model(f"anthropic:{model_name}", api_key=api_key)
            else:
                logger.warning(f"{log_prefix} Anthropic API key not configured in Settings")
        
        elif provider == "google":
            if api_key:
                logger.info(f"{log_prefix} Creating Google model: {model_name}")
                return init_chat_model(f"google_genai:{model_name}", api_key=api_key)
            else:
                logger.warning(f"{log_prefix} Google API key not configured in Settings")
        
        elif provider == "openrouter":
            if api_key and base_url:
                logger.info(f"{log_prefix} Creating OpenAI-compatible model: {model_name} at {base_url}")
                return ChatOpenAI(
                    model=model_name,
                    openai_api_base=base_url,
                    openai_api_key=api_key,
                )
            else:
                logger.warning(f"{log_prefix} OpenAI-compatible API not fully configured in Settings")
        
        elif provider == "bedrock":
            if not HAS_BEDROCK:
                logger.error(f"{log_prefix} langchain-aws not installed. Run: pip install langchain-aws")
                return None
            
            if aws_access_key_id and aws_secret_access_key:
                region = aws_region or "us-east-1"
                
                # Build Inference Profile ARN if account_id is provided and model_name is not already an ARN
                actual_model_id = model_name
                if aws_account_id and not model_name.startswith("arn:"):
                    # Build ARN: arn:aws:bedrock:{region}:{account_id}:inference-profile/us.{model_name}
                    actual_model_id = f"arn:aws:bedrock:{region}:{aws_account_id}:inference-profile/us.{model_name}"
                    logger.info(f"{log_prefix} Built Inference Profile ARN: {actual_model_id}")
                
                logger.info(f"{log_prefix} Creating AWS Bedrock model: {actual_model_id} in {region}")
                # Detect provider from model name/ARN for tool binding
                bedrock_provider = None
                if "anthropic" in model_name.lower():
                    bedrock_provider = "anthropic"
                elif "amazon" in model_name.lower():
                    bedrock_provider = "amazon"
                elif "meta" in model_name.lower():
                    bedrock_provider = "meta"
                elif "mistral" in model_name.lower():
                    bedrock_provider = "mistral"
                elif "cohere" in model_name.lower():
                    bedrock_provider = "cohere"
                
                return ChatBedrock(
                    model_id=actual_model_id,
                    region_name=region,
                    credentials_profile_name=None,
                    model_kwargs={},
                    aws_access_key_id=aws_access_key_id,
                    aws_secret_access_key=aws_secret_access_key,
                    provider=bedrock_provider,
                )
            else:
                logger.warning(f"{log_prefix} AWS Bedrock credentials not configured in Settings")
        
        elif provider == "azure":
            if azure_base_url and azure_api_key:
                logger.info(f"{log_prefix} Creating Azure OpenAI model: {model_name} at {azure_base_url}")
                # Azure uses deployment name as model
                from langchain_openai import AzureChatOpenAI
                return AzureChatOpenAI(
                    deployment_name=model_name,
                    azure_endpoint=azure_base_url,
                    api_key=azure_api_key,
                    api_version="2024-02-15-preview",
                )
            else:
                logger.warning(f"{log_prefix} Azure OpenAI not fully configured in Settings")
        
        logger.warning(f"{log_prefix} Could not create model for provider={provider}. Please configure in Settings.")
        return None
        
    except Exception as e:
        logger.error(f"{log_prefix} Error creating model: {e}")
        return None


def get_model_from_config() -> BaseChatModel | None:
    """Get model from config file.
    
    Returns:
        Configured model if config file is valid, None otherwise.
    """
    config = load_config_file()
    if not config:
        return None
    
    provider = config.get("provider")
    model_name = config.get("model")
    api_key = config.get("api_key")
    base_url = config.get("base_url")
    
    # AWS Bedrock specific
    aws_access_key_id = config.get("aws_access_key_id")
    aws_secret_access_key = config.get("aws_secret_access_key")
    aws_region = config.get("aws_region")
    aws_account_id = config.get("aws_account_id")
    
    # Azure specific
    azure_base_url = config.get("azure_base_url")
    azure_api_key = config.get("azure_api_key")
    
    return create_model_from_params(
        provider=provider,
        model_name=model_name,
        api_key=api_key,
        base_url=base_url,
        label="Primary",
        aws_access_key_id=aws_access_key_id,
        aws_secret_access_key=aws_secret_access_key,
        aws_region=aws_region,
        aws_account_id=aws_account_id,
        azure_base_url=azure_base_url,
        azure_api_key=azure_api_key,
    )


def get_model_from_env() -> BaseChatModel | None:
    """Get model from environment variables (deprecated, only for debugging).
    
    NOTE: All API keys should be configured via the Settings UI.
    Environment variables are only used as a last resort for debugging.
    
    Returns:
        Configured model if MODEL_NAME env var is set, None otherwise.
    """
    # Only support MODEL_NAME for debugging (no API keys from env)
    model_name = os.environ.get("MODEL_NAME")
    if model_name:
        logger.info(f"[MODEL CONFIG] Using MODEL_NAME from env (debug): {model_name}")
        return init_chat_model(model_name)
    
    # All API keys should come from Settings UI (model_config.json)
    # Do not read API keys from environment variables
    return None


def get_default_model() -> BaseChatModel:
    """Get the default model with priority: config file > env vars > fallback.
    
    Returns:
        Configured model instance.
    """
    # Priority 1: Config file (from frontend Settings)
    model = get_model_from_config()
    if model:
        return model
    
    # Priority 2: Environment variables
    model = get_model_from_env()
    if model:
        return model
    
    # Priority 3: Default fallback
    logger.info("[MODEL CONFIG] No config found, using default Google Gemini model")
    return init_chat_model("google_genai:gemini-2.0-flash")


# ============================================================
# Subagent Model Configuration
# ============================================================

def get_subagent_model(subagent_name: str, primary_model: BaseChatModel) -> BaseChatModel:
    """Get model for a specific subagent.
    
    Args:
        subagent_name: Name of the subagent (e.g., "general-purpose")
        primary_model: Primary model to inherit from if no override
    
    Returns:
        Model instance for the subagent.
    """
    config = load_config_file()
    if not config:
        return primary_model
    
    # Check for model override
    model_overrides = config.get("model_overrides", {})
    subagent_overrides = model_overrides.get("subagents", {})
    
    # Get override for this specific subagent
    override_model = subagent_overrides.get(subagent_name)
    
    # If no override or explicitly null/None, inherit from primary
    if not override_model:
        logger.info(f"[MODEL CONFIG] [Subagent:{subagent_name}] Inheriting from Primary")
        return primary_model
    
    # Create custom model for subagent
    logger.info(f"[MODEL CONFIG] [Subagent:{subagent_name}] Using override: {override_model}")
    
    # Use same provider/credentials as primary, but different model
    provider = config.get("provider")
    api_key = config.get("api_key")
    base_url = config.get("base_url")
    
    # AWS Bedrock specific
    aws_access_key_id = config.get("aws_access_key_id")
    aws_secret_access_key = config.get("aws_secret_access_key")
    aws_region = config.get("aws_region")
    aws_account_id = config.get("aws_account_id")
    
    # Azure specific
    azure_base_url = config.get("azure_base_url")
    azure_api_key = config.get("azure_api_key")
    
    subagent_model = create_model_from_params(
        provider=provider,
        model_name=override_model,
        api_key=api_key,
        base_url=base_url,
        label=f"Subagent:{subagent_name}",
        aws_access_key_id=aws_access_key_id,
        aws_secret_access_key=aws_secret_access_key,
        aws_region=aws_region,
        aws_account_id=aws_account_id,
        azure_base_url=azure_base_url,
        azure_api_key=azure_api_key,
    )
    
    return subagent_model if subagent_model else primary_model


def build_custom_subagents(primary_model: BaseChatModel) -> list[dict[str, Any]]:
    """Build custom subagents with model overrides.
    
    This creates a general-purpose subagent with a potentially different model.
    By passing it as a custom subagent, it will override the auto-generated one.
    
    Args:
        primary_model: Primary model for inheritance
    
    Returns:
        List of subagent configurations.
    """
    subagents = []
    
    # Create general-purpose subagent with potential model override
    gp_model = get_subagent_model("general-purpose", primary_model)
    
    # Only create custom subagent if model is different from primary
    if gp_model is not primary_model:
        subagents.append({
            "name": "general-purpose",
            "description": "General purpose subagent for complex, multi-step tasks. Has access to all tools.",
            "system_prompt": DEFAULT_SUBAGENT_PROMPT,
            "model": gp_model,
            "tools": [],  # Will use default tools
        })
        logger.info("[MODEL CONFIG] Created custom general-purpose subagent with different model")
    else:
        logger.info("[MODEL CONFIG] Using default general-purpose subagent (same model as primary)")
    
    return subagents


# ============================================================
# Tool Enable/Disable Configuration
# ============================================================

def get_enabled_tools() -> dict:
    """Get enabled tools configuration from model_config.json.
    
    Returns:
        Dictionary with tool names as keys and boolean enabled status.
        Default: all tools enabled.
    """
    default_config = {
        "fetch_url": True,
        # SerpAPI tools
        "serpapi_search": True,
        # Exa tools
        "exa_search": True,
        "exa_contents": True,
        "exa_find_similar": True,
        "exa_answer": True,
        "exa_research": True,
        # Tavily tools
        "tavily_search": True,
        "tavily_extract": True,
        "tavily_map": True,
        "tavily_crawl": True,
        # Perplexity tools
        "perplexity_search": True,
        "perplexity_chat": True,
    }
    
    try:
        if CONFIG_FILE.exists():
            with open(CONFIG_FILE) as f:
                config = json.load(f)
                enabled_tools = config.get("enabled_tools", {})
                # Merge with defaults (missing keys default to True)
                for key in default_config:
                    if key not in enabled_tools:
                        enabled_tools[key] = default_config[key]
                return enabled_tools
    except Exception as e:
        logger.warning(f"[TOOLS] Error reading enabled_tools config: {e}")
    
    return default_config


# ============================================================
# SerpAPI Google Search Tools
# ============================================================

def get_serp_tools() -> list:
    """Get SerpAPI tools if API key is configured.
    
    Returns:
        List of tools if SerpAPI is configured, empty list otherwise.
        
    Available tools:
        - serp_search: Unified search via engine parameter (google, google_news, google_images, google_maps, etc.)
    """
    config = load_config_file()
    serp_api_key = config.get("serp_api_key") if config else None
    
    if not serp_api_key:
        serp_api_key = os.environ.get("SERP_API_KEY") or os.environ.get("SERPAPI_API_KEY")
    
    if not serp_api_key:
        logger.info("[SERPAPI] No SerpAPI key configured, Google search disabled")
        return []
    
    try:
        import requests
        
        BASE_URL = "https://serpapi.com/search"
        
        def _serp_request(params: dict) -> dict:
            """Helper function to make SerpAPI requests."""
            try:
                params["api_key"] = serp_api_key
                response = requests.get(BASE_URL, params=params, timeout=60)
                response.raise_for_status()
                return response.json()
            except requests.exceptions.RequestException as e:
                return {"error": str(e)}
        
        # ============================================================
        # Unified Search Tool
        # ============================================================
        def serp_search(
            query: str,
            engine: str = "google",
            num_results: int = 10,
            location: str = None,
            lang: str = "en"
        ) -> dict:
            """Search using SerpAPI with different engines.
            
            Args:
                query: Search query string
                engine: Search engine to use. Options:
                    - "google": Web search (default)
                    - "google_news": News articles
                    - "google_images": Image search
                    - "google_maps": Local businesses/places
                    - "google_scholar": Academic papers
                    - "google_shopping": Shopping results
                    - "youtube": YouTube videos
                    - "bing": Bing web search
                    - "baidu": Baidu search
                num_results: Number of results to return (default 10)
                location: Location for localized results (optional)
                lang: Language code (default "en")
            
            Returns:
                Dictionary containing search results
            """
            params = {
                "engine": engine,
                "q": query,
                "num": num_results,
                "hl": lang
            }
            if location:
                params["location"] = location
            return _serp_request(params)
        
        # Filter tools based on enabled_tools config
        enabled = get_enabled_tools()
        tools = []
        tool_names = []
        
        if enabled.get("serpapi_search", True):
            tools.append(serp_search)
            tool_names.append("serp_search")
        
        logger.info(f"[SERPAPI] Loaded {len(tools)} SerpAPI tools: {', '.join(tool_names)}")
        return tools
        
    except Exception as e:
        logger.error(f"[SERPAPI] Failed to initialize SerpAPI tools: {e}")
        return []


# ============================================================
# Exa Neural Search Tools
# ============================================================

def get_exa_tools() -> list:
    """Get Exa API tools if API key is configured.
    
    Returns:
        List of tools if Exa is configured, empty list otherwise.
        
    Available tools:
        - exa_search: Neural/keyword search for web pages
        - exa_contents: Get clean content from URLs
        - exa_find_similar: Find semantically similar pages
        - exa_answer: Get direct answers with citations
        - exa_research: Automate in-depth web research with citations
    """
    config = load_config_file()
    exa_api_key = config.get("exa_api_key") if config else None
    
    if not exa_api_key:
        exa_api_key = os.environ.get("EXA_API_KEY")
    
    if not exa_api_key:
        logger.info("[EXA] No Exa API key configured, neural search disabled")
        return []
    
    try:
        import requests
        
        BASE_URL = "https://api.exa.ai"
        headers = {
            "x-api-key": exa_api_key,
            "Content-Type": "application/json"
        }
        
        def _exa_request(endpoint: str, payload: dict) -> dict:
            """Helper function to make Exa API requests."""
            try:
                response = requests.post(
                    f"{BASE_URL}/{endpoint}",
                    headers=headers,
                    json=payload,
                    timeout=60
                )
                response.raise_for_status()
                return response.json()
            except requests.exceptions.RequestException as e:
                return {"error": str(e)}
        
        # ============================================================
        # Tool 1: Exa Search
        # ============================================================
        def exa_search(
            query: str,
            num_results: int = 10,
            search_type: str = "auto",
            use_autoprompt: bool = True,
            include_text: bool = True,
            include_highlights: bool = True
        ) -> dict:
            """Search the web using Exa's neural/keyword search.
            
            Args:
                query: Search query string
                num_results: Number of results to return (default 10)
                search_type: "neural", "keyword", or "auto" (default "auto")
                use_autoprompt: Automatically optimize query (default True)
                include_text: Include page text content (default True)
                include_highlights: Include highlighted snippets (default True)
            
            Returns:
                Dictionary containing search results with titles, URLs, and content
            """
            payload = {
                "query": query,
                "numResults": num_results,
                "type": search_type,
                "useAutoprompt": use_autoprompt,
                "contents": {
                    "text": include_text,
                    "highlights": include_highlights
                }
            }
            return _exa_request("search", payload)
        
        # ============================================================
        # Tool 2: Exa Contents
        # ============================================================
        def exa_contents(
            urls: list,
            include_text: bool = True,
            include_highlights: bool = False,
            highlight_query: str = None
        ) -> dict:
            """Get clean, parsed content from URLs.
            
            Args:
                urls: List of URLs to get content from
                include_text: Include main text content (default True)
                include_highlights: Include highlighted snippets (default False)
                highlight_query: Query for generating highlights (optional)
            
            Returns:
                Dictionary containing parsed content from each URL
            """
            payload = {
                "ids": urls,
                "text": include_text,
                "highlights": include_highlights
            }
            if highlight_query:
                payload["highlightQuery"] = highlight_query
            return _exa_request("contents", payload)
        
        # ============================================================
        # Tool 3: Exa Find Similar
        # ============================================================
        def exa_find_similar(
            url: str,
            num_results: int = 10,
            include_text: bool = True,
            exclude_source_domain: bool = True
        ) -> dict:
            """Find web pages semantically similar to a given URL.
            
            Args:
                url: URL to find similar pages for
                num_results: Number of similar pages to return (default 10)
                include_text: Include page text content (default True)
                exclude_source_domain: Exclude pages from the same domain (default True)
            
            Returns:
                Dictionary containing similar pages with titles, URLs, and content
            """
            payload = {
                "url": url,
                "numResults": num_results,
                "excludeSourceDomain": exclude_source_domain,
                "contents": {
                    "text": include_text
                }
            }
            return _exa_request("findSimilar", payload)
        
        # ============================================================
        # Tool 4: Exa Answer
        # ============================================================
        def exa_answer(
            query: str,
            text: bool = True
        ) -> dict:
            """Get direct answers to questions with citations.
            
            Args:
                query: Question to answer
                text: Include source text (default True)
            
            Returns:
                Dictionary containing answer with citations
            """
            payload = {
                "query": query,
                "text": text
            }
            return _exa_request("answer", payload)
        
        # ============================================================
        # Tool 5: Exa Research
        # ============================================================
        def exa_research(
            query: str,
            model: str = "exa-research"
        ) -> dict:
            """Automate in-depth web research and receive structured JSON results with citations.
            
            Args:
                query: Research topic or question
                model: Model to use - "exa-research" (standard) or "exa-research-pro" (advanced)
            
            Returns:
                Dictionary containing structured research results with citations
            """
            # Research endpoint uses OpenAI-compatible chat completions format
            try:
                response = requests.post(
                    f"{BASE_URL}/chat/completions",
                    headers=headers,
                    json={
                        "model": model,
                        "messages": [
                            {"role": "user", "content": query}
                        ]
                    },
                    timeout=120  # Research takes longer
                )
                response.raise_for_status()
                return response.json()
            except requests.exceptions.RequestException as e:
                return {"error": str(e)}
        
        # Filter tools based on enabled_tools config
        enabled = get_enabled_tools()
        tools = []
        tool_names = []
        
        if enabled.get("exa_search", True):
            tools.append(exa_search)
            tool_names.append("exa_search")
        if enabled.get("exa_contents", True):
            tools.append(exa_contents)
            tool_names.append("exa_contents")
        if enabled.get("exa_find_similar", True):
            tools.append(exa_find_similar)
            tool_names.append("exa_find_similar")
        if enabled.get("exa_answer", True):
            tools.append(exa_answer)
            tool_names.append("exa_answer")
        if enabled.get("exa_research", True):
            tools.append(exa_research)
            tool_names.append("exa_research")
        
        logger.info(f"[EXA] Loaded {len(tools)} Exa tools: {', '.join(tool_names)}")
        return tools
        
    except Exception as e:
        logger.error(f"[EXA] Failed to initialize Exa tools: {e}")
        return []


# ============================================================
# Web Search Tools (Tavily)
# ============================================================

def get_tavily_tools() -> list:
    """Get Tavily API tools if API key is configured.
    
    Returns:
        List of tools if Tavily is configured, empty list otherwise.
        
    Available tools (matching Tavily API endpoints):
        - tavily_search: /search - Search the web for information
        - tavily_extract: /extract - Extract content from URLs
        - tavily_map: /map - Discover website structure and internal links
        - tavily_crawl: /crawl - Crawl and extract content from entire website
    """
    config = load_config_file()
    tavily_api_key = config.get("tavily_api_key") if config else None
    
    if not tavily_api_key:
        # Also check environment variable
        tavily_api_key = os.environ.get("TAVILY_API_KEY")
    
    if not tavily_api_key:
        logger.info("[TAVILY] No Tavily API key configured, web search disabled")
        return []
    
    # Set environment variable for any libraries that need it
    os.environ["TAVILY_API_KEY"] = tavily_api_key
    
    try:
        from tavily import TavilyClient
        import requests
        from markdownify import markdownify
        
        tavily_client = TavilyClient(api_key=tavily_api_key)
        
        # ============================================================
        # Tool 1: Tavily Search (/search endpoint)
        # ============================================================
        def tavily_search(
            query: str,
            max_results: int = 5,
        ) -> dict:
            """Search the web using Tavily /search endpoint.
            
            Args:
                query: Search query string
                max_results: Maximum number of results to return (default 5)
            
            Returns:
                Dictionary containing search results with titles, URLs, and content snippets
            """
            try:
                response = tavily_client.search(
                    query=query,
                    max_results=max_results,
                    include_raw_content=False,
                )
                
                results = []
                for result in response.get("results", []):
                    results.append({
                        "title": result.get("title", ""),
                        "url": result.get("url", ""),
                        "content": result.get("content", ""),
                    })
                
                return {
                    "success": True,
                    "query": query,
                    "results": results,
                    "answer": response.get("answer", ""),
                }
            except Exception as e:
                return {
                    "success": False,
                    "query": query,
                    "error": str(e),
                    "results": [],
                }
        
        # ============================================================
        # Tool 2: Tavily Extract (/extract endpoint)
        # ============================================================
        def tavily_extract(
            urls: list[str],
            include_images: bool = False,
        ) -> dict:
            """Extract content from URLs using Tavily /extract endpoint.
            
            Handles JavaScript-rendered pages and complex layouts.
            Can extract from single URL or multiple URLs (max 20).
            
            Args:
                urls: List of URLs to extract content from (max 20)
                include_images: Whether to include extracted images (default False)
            
            Returns:
                Dictionary containing extracted content from each URL
            """
            try:
                # Limit to 20 URLs as per Tavily API
                urls = urls[:20]
                
                response = tavily_client.extract(
                    urls=urls,
                    include_images=include_images,
                )
                
                results = []
                for result in response.get("results", []):
                    results.append({
                        "url": result.get("url", ""),
                        "content": result.get("raw_content", "")[:30000],  # Limit content
                        "images": result.get("images", []) if include_images else [],
                    })
                
                return {
                    "success": True,
                    "urls_requested": len(urls),
                    "urls_extracted": len(results),
                    "results": results,
                }
            except Exception as e:
                return {
                    "success": False,
                    "error": str(e),
                    "results": [],
                }
        
        # ============================================================
        # Tool 3: Tavily Map (/map endpoint)
        # ============================================================
        def tavily_map(
            url: str,
            max_depth: int = 2,
            limit: int = 50,
        ) -> dict:
            """Discover and map the structure of a website using Tavily /map endpoint.
            
            Use this to understand a website's structure before crawling.
            Returns all internal links found starting from the base URL.
            
            Args:
                url: The root URL to start mapping from
                max_depth: How many levels deep to explore (default 2)
                limit: Maximum number of URLs to return (default 50)
            
            Returns:
                Dictionary containing list of discovered URLs
            """
            try:
                response = tavily_client.map(
                    url=url,
                    max_depth=max_depth,
                    limit=limit,
                )
                
                discovered_urls = response.get("results", [])
                
                return {
                    "success": True,
                    "base_url": url,
                    "max_depth": max_depth,
                    "urls_found": len(discovered_urls),
                    "urls": discovered_urls,
                }
            except Exception as e:
                return {
                    "success": False,
                    "base_url": url,
                    "error": str(e),
                    "urls": [],
                }
        
        # ============================================================
        # Tool 4: Tavily Crawl (/crawl endpoint)
        # ============================================================
        def tavily_crawl(
            url: str,
            max_depth: int = 2,
            limit: int = 20,
            instructions: str = "",
        ) -> dict:
            """Crawl a website and extract content using Tavily /crawl endpoint.
            
            Automatically follows internal links and extracts content.
            Use this for building knowledge bases or comprehensive research.
            
            Args:
                url: The starting URL to begin crawling
                max_depth: How many levels deep to crawl (default 2)
                limit: Maximum number of pages to crawl (default 20)
                instructions: Optional instructions to filter pages (e.g., "Find all product pages")
            
            Returns:
                Dictionary containing crawled pages with their content
            """
            try:
                crawl_params = {
                    "url": url,
                    "max_depth": max_depth,
                    "limit": limit,
                }
                if instructions:
                    crawl_params["instructions"] = instructions
                
                response = tavily_client.crawl(**crawl_params)
                
                results = []
                for result in response.get("results", []):
                    results.append({
                        "url": result.get("url", ""),
                        "title": result.get("title", ""),
                        "content": result.get("raw_content", "")[:20000],  # Limit per page
                    })
                
                return {
                    "success": True,
                    "start_url": url,
                    "pages_crawled": len(results),
                    "max_depth": max_depth,
                    "instructions": instructions or "None",
                    "results": results,
                }
            except Exception as e:
                return {
                    "success": False,
                    "start_url": url,
                    "error": str(e),
                    "results": [],
                }
        
        # Filter tools based on enabled_tools config
        enabled = get_enabled_tools()
        tools = []
        tool_names = []
        
        if enabled.get("tavily_search", True):
            tools.append(tavily_search)
            tool_names.append("tavily_search")
        if enabled.get("tavily_extract", True):
            tools.append(tavily_extract)
            tool_names.append("tavily_extract")
        if enabled.get("tavily_map", True):
            tools.append(tavily_map)
            tool_names.append("tavily_map")
        if enabled.get("tavily_crawl", True):
            tools.append(tavily_crawl)
            tool_names.append("tavily_crawl")
        
        if tools:
            logger.info(f"[TAVILY] Tools enabled: {', '.join(tool_names)}")
        else:
            logger.info("[TAVILY] All Tavily tools disabled by config")
        
        return tools
        
    except ImportError as e:
        logger.warning(f"[TAVILY] Required packages not installed: {e}")
        logger.warning("[TAVILY] Run: pip install tavily-python markdownify requests")
        return []
    except Exception as e:
        logger.error(f"[TAVILY] Error initializing tools: {e}")
        return []


# ============================================================
# Perplexity Sonar Tools
# ============================================================

def get_perplexity_tools() -> list:
    """Get Perplexity API tools if API key is configured.
    
    Perplexity provides two main endpoints:
    - /search: Returns raw search results (URLs, metadata)
    - /chat/completions: AI-generated answers with citations (via model parameter)
    
    Returns:
        List of tools if Perplexity is configured, empty list otherwise.
        
    Available tools:
        - perplexity_search: Raw search results via /search endpoint
        - perplexity_chat: AI answers via /chat/completions endpoint
    """
    config = load_config_file()
    perplexity_api_key = config.get("perplexity_api_key") if config else None
    
    if not perplexity_api_key:
        perplexity_api_key = os.environ.get("PERPLEXITY_API_KEY")
    
    if not perplexity_api_key:
        logger.info("[PERPLEXITY] No Perplexity API key configured")
        return []
    
    try:
        import requests
        
        BASE_URL = "https://api.perplexity.ai"
        headers = {
            "Authorization": f"Bearer {perplexity_api_key}",
            "Content-Type": "application/json"
        }
        
        # ============================================================
        # Tool 1: Perplexity Search (/search endpoint)
        # ============================================================
        def perplexity_search(
            query: str,
            num_results: int = 10
        ) -> dict:
            """Search the web using Perplexity's /search endpoint.
            
            Returns raw search results with URLs and metadata, without AI summarization.
            Use this when you need source URLs for further processing.
            
            Args:
                query: Search query string
                num_results: Number of results to return (default 10)
            
            Returns:
                Dictionary containing search results with URLs and metadata
            """
            try:
                response = requests.post(
                    f"{BASE_URL}/search",
                    headers=headers,
                    json={
                        "query": query,
                        "num_results": num_results
                    },
                    timeout=60
                )
                response.raise_for_status()
                return response.json()
            except requests.exceptions.RequestException as e:
                return {"error": str(e)}
        
        # ============================================================
        # Tool 2: Perplexity Chat (/chat/completions endpoint)
        # ============================================================
        def perplexity_chat(
            query: str,
            model: str = "sonar",
            search_mode: str = "web",
            recency_filter: str = None,
            domains: list[str] | None = None,
            return_images: bool = False,
            return_related_questions: bool = False
        ) -> dict:
            """Get AI-generated answers using Perplexity's /chat/completions endpoint.
            
            Returns synthesized answers with citations based on web search.
            
            Args:
                query: The question or search query
                model: Model to use. Options:
                    - "sonar": Lightweight search (default)
                    - "sonar-pro": Advanced search
                    - "sonar-deep-research": Exhaustive research
                    - "sonar-reasoning": Fast reasoning
                    - "sonar-reasoning-pro": Premier reasoning
                search_mode: Search mode - "web" (default), "academic", or "sec"
                recency_filter: Time filter - "day", "week", "month", or "year"
                domains: Domain filter list (max 20, prefix with - to exclude)
                return_images: Include images in response
                return_related_questions: Include related questions
            
            Returns:
                Dictionary containing AI answer with citations
            """
            try:
                payload = {
                    "model": model,
                    "messages": [{"role": "user", "content": query}],
                    "search_mode": search_mode,
                    "temperature": 0.2,
                    "return_images": return_images,
                    "return_related_questions": return_related_questions
                }
                
                if recency_filter and recency_filter in ["day", "week", "month", "year"]:
                    payload["search_recency_filter"] = recency_filter
                
                if domains and len(domains) > 0:
                    payload["search_domain_filter"] = domains[:20]
                
                response = requests.post(
                    f"{BASE_URL}/chat/completions",
                    headers=headers,
                    json=payload,
                    timeout=120
                )
                response.raise_for_status()
                result = response.json()
                
                # Extract answer
                answer = ""
                if "choices" in result and len(result["choices"]) > 0:
                    answer = result["choices"][0].get("message", {}).get("content", "")
                
                return {
                    "success": True,
                    "query": query,
                    "answer": answer,
                    "model": model,
                    "search_results": result.get("search_results", []),
                    "usage": result.get("usage", {}),
                    "raw_response": result
                }
            except requests.exceptions.RequestException as e:
                return {
                    "success": False,
                    "query": query,
                    "error": str(e),
                    "answer": ""
                }
        
        # Filter tools based on enabled_tools config
        enabled = get_enabled_tools()
        tools = []
        tool_names = []
        
        if enabled.get("perplexity_search", True):
            tools.append(perplexity_search)
            tool_names.append("perplexity_search")
        if enabled.get("perplexity_chat", True):
            tools.append(perplexity_chat)
            tool_names.append("perplexity_chat")
        
        if tools:
            logger.info(f"[PERPLEXITY] Tools enabled: {', '.join(tool_names)}")
        else:
            logger.info("[PERPLEXITY] All Perplexity tools disabled by config")
        
        return tools
        
    except Exception as e:
        logger.error(f"[PERPLEXITY] Error initializing tools: {e}")
        return []


# ============================================================
# Built-in Tools (no API key required)
# ============================================================

def get_builtin_tools() -> list:
    """Get built-in tools that don't require any API key.
    
    Returns:
        List of built-in tools (filtered by enabled_tools config).
        
    Available tools:
        - fetch_url: Fetch URL content and convert to markdown
    """
    enabled = get_enabled_tools()
    tools = []
    
    # Only add fetch_url if enabled
    if not enabled.get("fetch_url", True):
        logger.info("[BUILTIN] fetch_url disabled by config")
        return tools
    
    try:
        import requests
        from markdownify import markdownify
        
        def fetch_url(url: str, timeout: int = 30) -> dict:
            """Fetch content from a URL and convert HTML to markdown.
            
            Use this to read web page content. The HTML is automatically
            converted to clean markdown for easy processing.
            
            Args:
                url: The URL to fetch (must be HTTP/HTTPS)
                timeout: Request timeout in seconds (default 30)
            
            Returns:
                Dictionary containing the page content as markdown
            """
            try:
                headers = {
                    "User-Agent": "Mozilla/5.0 (compatible; DeepAgents/1.0)"
                }
                response = requests.get(url, headers=headers, timeout=timeout)
                response.raise_for_status()
                
                content_type = response.headers.get("content-type", "")
                if "text/html" in content_type:
                    markdown_content = markdownify(response.text, heading_style="ATX")
                else:
                    markdown_content = response.text
                
                return {
                    "success": True,
                    "url": str(response.url),
                    "content": markdown_content[:50000],  # Limit content length
                    "content_type": content_type,
                    "content_length": len(markdown_content),
                }
            except Exception as e:
                return {
                    "success": False,
                    "url": url,
                    "error": str(e),
                }
        
        tools.append(fetch_url)
        logger.info("[BUILTIN] Built-in tools enabled (fetch_url)")
        return tools
        
    except ImportError as e:
        logger.warning(f"[BUILTIN] Required packages not installed: {e}")
        return []
    except Exception as e:
        logger.error(f"[BUILTIN] Error initializing tools: {e}")
        return []


# ============================================================
# Agent Initialization
# ============================================================

print("=" * 60)
print("AGENT.PY LOADING")
print(f"  Config file: {CONFIG_FILE}")
print(f"  Config exists: {CONFIG_FILE.exists()}")
print("=" * 60)

# Create primary model from config file or environment
default_model = get_default_model()

# Build custom subagents with model overrides
custom_subagents = build_custom_subagents(default_model)

# Get all tools
builtin_tools = get_builtin_tools()
serp_tools = get_serp_tools()
exa_tools = get_exa_tools()
tavily_tools = get_tavily_tools()
perplexity_tools = get_perplexity_tools()

# Combine all tools
all_tools = builtin_tools + serp_tools + exa_tools + tavily_tools + perplexity_tools

# Create the deep agent
agent = create_deep_agent(
    model=default_model,
    tools=all_tools if all_tools else None,
    system_prompt="You are a helpful AI assistant. Be concise and helpful in your responses.",
    subagents=custom_subagents if custom_subagents else None,
)

logger.info("[MODEL CONFIG] Agent created successfully")
print("=" * 60)
print("AGENT READY")
print(f"  Primary Model: {default_model}")
print(f"  Custom Subagents: {len(custom_subagents)}")

# Display Built-in tools status
if builtin_tools:
    print(f"  Built-in Tools: {len(builtin_tools)} enabled")
    tool_names = [t.__name__ for t in builtin_tools]
    print(f"    - {', '.join(tool_names)}")

# Display SerpAPI tools status
if serp_tools:
    print(f"  SerpAPI Tools: {len(serp_tools)} enabled")
    tool_names = [t.__name__ for t in serp_tools]
    print(f"    - {', '.join(tool_names)}")
else:
    print("  SerpAPI Tools: Disabled (no API key)")

# Display Exa tools status
if exa_tools:
    print(f"  Exa Tools: {len(exa_tools)} enabled")
    tool_names = [t.__name__ for t in exa_tools]
    print(f"    - {', '.join(tool_names)}")
else:
    print("  Exa Tools: Disabled (no API key)")

# Display Tavily tools status
if tavily_tools:
    print(f"  Tavily Tools: {len(tavily_tools)} enabled")
    tool_names = [t.__name__ for t in tavily_tools]
    print(f"    - {', '.join(tool_names)}")
else:
    print("  Tavily Tools: Disabled (no API key)")

# Display Perplexity tools status
if perplexity_tools:
    print(f"  Perplexity Tools: {len(perplexity_tools)} enabled")
    tool_names = [t.__name__ for t in perplexity_tools]
    print(f"    - {', '.join(tool_names)}")
else:
    print("  Perplexity Tools: Disabled (no API key)")

print(f"  Total Tools: {len(all_tools)}")
print("=" * 60)
