"""Simple deep agent with model configuration from config file.

Model Configuration Priority:
1. model_config.json (from frontend Settings UI) - highest priority
2. Environment variables (OPENAI_API_KEY, OPENAI_MODEL, etc.)
3. Default fallback (Google Gemini)

Hot Reload: In dev mode, LangGraph's watchfiles will automatically reload
when model_config.json is modified by the frontend.

Model Override Support:
- Primary Model: Used for main chat
- Subagents (including general-purpose): Can use different models via model_overrides
- Summarization: Inherits from Primary Model (deepagents library limitation)
- Suggestions: Handled by frontend directly
"""

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

from langchain.chat_models import init_chat_model
from langchain_core.language_models import BaseChatModel
from langchain_openai import ChatOpenAI

from deepagents import create_deep_agent
from deepagents.middleware.subagents import DEFAULT_SUBAGENT_PROMPT

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Config file path (same directory as agent.py)
CONFIG_FILE = Path(__file__).parent / "model_config.json"


def load_config_file() -> dict[str, Any] | None:
    """Load model configuration from JSON file.
    
    Returns:
        Configuration dict if file exists and is valid, None otherwise.
    """
    if not CONFIG_FILE.exists():
        logger.info(f"[MODEL CONFIG] Config file not found: {CONFIG_FILE}")
        return None
    
    try:
        with open(CONFIG_FILE, "r") as f:
            config = json.load(f)
        
        # Validate required fields
        if not config.get("provider") or not config.get("model"):
            logger.warning("[MODEL CONFIG] Config file missing provider or model")
            return None
        
        # Check if API key is set (either in file or env)
        api_key = config.get("api_key") or os.environ.get("OPENAI_API_KEY")
        if not api_key:
            logger.warning("[MODEL CONFIG] No API key found in config or environment")
            return None
        
        logger.info(f"[MODEL CONFIG] Loaded config from file: provider={config.get('provider')}, model={config.get('model')}")
        return config
        
    except json.JSONDecodeError as e:
        logger.error(f"[MODEL CONFIG] Invalid JSON in config file: {e}")
        return None
    except Exception as e:
        logger.error(f"[MODEL CONFIG] Error reading config file: {e}")
        return None


def save_config_file(config: dict[str, Any]) -> bool:
    """Save model configuration to JSON file.
    
    This function is called by the frontend API to persist settings.
    
    Args:
        config: Configuration dict with provider, model, api_key, etc.
    
    Returns:
        True if saved successfully, False otherwise.
    """
    try:
        config["_last_updated"] = datetime.now().isoformat()
        config["_comment"] = "This file is auto-generated by the frontend. Edit via Settings UI."
        
        with open(CONFIG_FILE, "w") as f:
            json.dump(config, f, indent=2)
        
        logger.info(f"[MODEL CONFIG] Saved config to file: {CONFIG_FILE}")
        return True
        
    except Exception as e:
        logger.error(f"[MODEL CONFIG] Error saving config file: {e}")
        return False


def create_model_from_params(
    provider: str,
    model_name: str,
    api_key: str | None = None,
    base_url: str | None = None,
    label: str = "",
) -> BaseChatModel | None:
    """Create a model instance from parameters.
    
    Args:
        provider: Provider name (openai, anthropic, google, openrouter)
        model_name: Model name/ID
        api_key: API key (optional, falls back to env vars)
        base_url: Base URL for OpenAI-compatible APIs
        label: Label for logging (e.g., "Primary", "Subagent")
    
    Returns:
        Configured model instance, or None if creation fails.
    """
    log_prefix = f"[MODEL CONFIG] [{label}]" if label else "[MODEL CONFIG]"
    
    try:
        if provider == "openai":
            key = api_key or os.environ.get("OPENAI_API_KEY")
            if key:
                logger.info(f"{log_prefix} Creating OpenAI model: {model_name}")
                return ChatOpenAI(model=model_name, openai_api_key=key)
        
        elif provider == "anthropic":
            key = api_key or os.environ.get("ANTHROPIC_API_KEY")
            if key:
                logger.info(f"{log_prefix} Creating Anthropic model: {model_name}")
                return init_chat_model(f"anthropic:{model_name}", api_key=key)
        
        elif provider == "google":
            key = api_key or os.environ.get("GOOGLE_API_KEY")
            if key:
                logger.info(f"{log_prefix} Creating Google model: {model_name}")
                return init_chat_model(f"google_genai:{model_name}", api_key=key)
        
        elif provider == "openrouter":
            key = api_key or os.environ.get("OPENAI_API_KEY")
            url = base_url or os.environ.get("OPENAI_BASE_URL")
            if key and url:
                logger.info(f"{log_prefix} Creating OpenAI-compatible model: {model_name} at {url}")
                return ChatOpenAI(
                    model=model_name,
                    openai_api_base=url,
                    openai_api_key=key,
                )
        
        logger.warning(f"{log_prefix} Could not create model for provider={provider}")
        return None
        
    except Exception as e:
        logger.error(f"{log_prefix} Error creating model: {e}")
        return None


def get_model_from_config() -> BaseChatModel | None:
    """Get model from config file.
    
    Returns:
        Configured model if config file is valid, None otherwise.
    """
    config = load_config_file()
    if not config:
        return None
    
    provider = config.get("provider")
    model_name = config.get("model")
    api_key = config.get("api_key")
    base_url = config.get("base_url")
    
    return create_model_from_params(
        provider=provider,
        model_name=model_name,
        api_key=api_key,
        base_url=base_url,
        label="Primary",
    )


def get_model_from_env() -> BaseChatModel | None:
    """Get model from environment variables.
    
    Returns:
        Configured model if environment variables are set, None otherwise.
    """
    # Check for explicit model name
    model_name = os.environ.get("MODEL_NAME")
    if model_name:
        logger.info(f"[MODEL CONFIG] Using MODEL_NAME from env: {model_name}")
        return init_chat_model(model_name)
    
    # Check for OpenAI-compatible API
    if os.environ.get("OPENAI_API_KEY"):
        openai_model = os.environ.get("OPENAI_MODEL", "gpt-4o")
        base_url = os.environ.get("OPENAI_BASE_URL")
        api_key = os.environ.get("OPENAI_API_KEY")
        
        logger.info(f"[MODEL CONFIG] Using OpenAI from env: model={openai_model}, base_url={base_url}")
        
        if base_url:
            return ChatOpenAI(
                model=openai_model,
                openai_api_base=base_url,
                openai_api_key=api_key,
            )
        return init_chat_model(f"openai:{openai_model}")
    
    # Check for Anthropic
    if os.environ.get("ANTHROPIC_API_KEY"):
        anthropic_model = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-5-20250929")
        logger.info(f"[MODEL CONFIG] Using Anthropic from env: {anthropic_model}")
        return init_chat_model(f"anthropic:{anthropic_model}")
    
    # Check for Google
    if os.environ.get("GOOGLE_API_KEY"):
        google_model = os.environ.get("GOOGLE_MODEL", "gemini-2.0-flash")
        logger.info(f"[MODEL CONFIG] Using Google from env: {google_model}")
        return init_chat_model(f"google_genai:{google_model}")
    
    return None


def get_default_model() -> BaseChatModel:
    """Get the default model with priority: config file > env vars > fallback.
    
    Returns:
        Configured model instance.
    """
    # Priority 1: Config file (from frontend Settings)
    model = get_model_from_config()
    if model:
        return model
    
    # Priority 2: Environment variables
    model = get_model_from_env()
    if model:
        return model
    
    # Priority 3: Default fallback
    logger.info("[MODEL CONFIG] No config found, using default Google Gemini model")
    return init_chat_model("google_genai:gemini-2.0-flash")


# ============================================================
# Subagent Model Configuration
# ============================================================

def get_subagent_model(subagent_name: str, primary_model: BaseChatModel) -> BaseChatModel:
    """Get model for a specific subagent.
    
    Args:
        subagent_name: Name of the subagent (e.g., "general-purpose")
        primary_model: Primary model to inherit from if no override
    
    Returns:
        Model instance for the subagent.
    """
    config = load_config_file()
    if not config:
        return primary_model
    
    # Check for model override
    model_overrides = config.get("model_overrides", {})
    subagent_overrides = model_overrides.get("subagents", {})
    
    # Get override for this specific subagent
    override_model = subagent_overrides.get(subagent_name)
    
    # If no override or explicitly null/None, inherit from primary
    if not override_model:
        logger.info(f"[MODEL CONFIG] [Subagent:{subagent_name}] Inheriting from Primary")
        return primary_model
    
    # Create custom model for subagent
    logger.info(f"[MODEL CONFIG] [Subagent:{subagent_name}] Using override: {override_model}")
    
    # Use same provider/api_key/base_url as primary, but different model
    provider = config.get("provider")
    api_key = config.get("api_key")
    base_url = config.get("base_url")
    
    subagent_model = create_model_from_params(
        provider=provider,
        model_name=override_model,
        api_key=api_key,
        base_url=base_url,
        label=f"Subagent:{subagent_name}",
    )
    
    return subagent_model if subagent_model else primary_model


def build_custom_subagents(primary_model: BaseChatModel) -> list[dict[str, Any]]:
    """Build custom subagents with model overrides.
    
    This creates a general-purpose subagent with a potentially different model.
    By passing it as a custom subagent, it will override the auto-generated one.
    
    Args:
        primary_model: Primary model for inheritance
    
    Returns:
        List of subagent configurations.
    """
    subagents = []
    
    # Create general-purpose subagent with potential model override
    gp_model = get_subagent_model("general-purpose", primary_model)
    
    # Only create custom subagent if model is different from primary
    if gp_model is not primary_model:
        subagents.append({
            "name": "general-purpose",
            "description": "General purpose subagent for complex, multi-step tasks. Has access to all tools.",
            "system_prompt": DEFAULT_SUBAGENT_PROMPT,
            "model": gp_model,
            "tools": [],  # Will use default tools
        })
        logger.info("[MODEL CONFIG] Created custom general-purpose subagent with different model")
    else:
        logger.info("[MODEL CONFIG] Using default general-purpose subagent (same model as primary)")
    
    return subagents


# ============================================================
# Agent Initialization
# ============================================================

print("=" * 60)
print("AGENT.PY LOADING")
print(f"  Config file: {CONFIG_FILE}")
print(f"  Config exists: {CONFIG_FILE.exists()}")
print("=" * 60)

# Create primary model from config file or environment
default_model = get_default_model()

# Build custom subagents with model overrides
custom_subagents = build_custom_subagents(default_model)

# Create the deep agent
agent = create_deep_agent(
    model=default_model,
    system_prompt="You are a helpful AI assistant. Be concise and helpful in your responses.",
    subagents=custom_subagents if custom_subagents else None,
)

logger.info("[MODEL CONFIG] Agent created successfully")
print("=" * 60)
print("AGENT READY")
print(f"  Primary Model: {default_model}")
print(f"  Custom Subagents: {len(custom_subagents)}")
print("=" * 60)
