"""Simple config server for saving model configuration.

This server runs alongside LangGraph dev and provides an API
to save model configuration to model_config.json.

When the config file is updated, LangGraph's watchfiles will
automatically detect the change and reload the agent.

Run with:
    python config_server.py
"""

import json
import os
from datetime import datetime
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path

# Config file path
CONFIG_FILE = Path(__file__).parent / "model_config.json"
PORT = 2025


class ConfigHandler(BaseHTTPRequestHandler):
    """HTTP request handler for config API."""
    
    def _send_cors_headers(self):
        """Send CORS headers."""
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
    
    def _send_json(self, data: dict, status: int = 200):
        """Send JSON response."""
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self._send_cors_headers()
        self.end_headers()
        self.wfile.write(json.dumps(data).encode())
    
    def do_OPTIONS(self):
        """Handle CORS preflight."""
        self.send_response(200)
        self._send_cors_headers()
        self.end_headers()
    
    def do_GET(self):
        """Handle GET requests."""
        if self.path == "/":
            self._send_json({
                "status": "ok",
                "config_file": str(CONFIG_FILE),
                "message": "Config server running. POST to /config to save."
            })
        elif self.path == "/config":
            if not CONFIG_FILE.exists():
                self._send_json({"error": "Config file not found", "config": None})
                return
            
            try:
                with open(CONFIG_FILE, "r") as f:
                    config = json.load(f)
                self._send_json({"config": config})
            except Exception as e:
                self._send_json({"error": str(e)}, 500)
        else:
            self._send_json({"error": "Not found"}, 404)
    
    def do_POST(self):
        """Handle POST requests."""
        if self.path == "/config":
            try:
                content_length = int(self.headers.get("Content-Length", 0))
                body = self.rfile.read(content_length).decode()
                config = json.loads(body)
                
                # Add metadata
                config["_last_updated"] = datetime.now().isoformat()
                config["_comment"] = "Auto-generated by frontend. Edit via Settings UI."
                
                # Save to file
                with open(CONFIG_FILE, "w") as f:
                    json.dump(config, f, indent=2)
                
                print(f"[CONFIG] Saved config: provider={config.get('provider')}, model={config.get('model')}")
                
                self._send_json({
                    "success": True,
                    "message": "Config saved. LangGraph will reload automatically in dev mode.",
                    "config": config,
                })
            except Exception as e:
                print(f"[CONFIG] Error saving config: {e}")
                self._send_json({"error": str(e)}, 500)
        elif self.path == "/reload":
            try:
                # Touch agent.py to trigger watchfiles reload
                agent_file = Path(__file__).parent / "agent.py"
                if agent_file.exists():
                    agent_file.touch()
                    print("[CONFIG] Triggered hot reload by touching agent.py")
                    self._send_json({
                        "success": True,
                        "message": "Hot reload triggered. LangGraph will reload in a moment.",
                    })
                else:
                    self._send_json({"error": "agent.py not found"}, 404)
            except Exception as e:
                print(f"[CONFIG] Error triggering reload: {e}")
                self._send_json({"error": str(e)}, 500)
        elif self.path == "/restart":
            import subprocess
            import socket
            import time
            
            def is_backend_running(port=2024):
                """Check if backend is running on the given port."""
                try:
                    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                    sock.settimeout(1)
                    result = sock.connect_ex(('127.0.0.1', port))
                    sock.close()
                    return result == 0
                except:
                    return False
            
            try:
                was_running = is_backend_running()
                
                if was_running:
                    # Kill existing process
                    print("[CONFIG] Backend is running, killing it first...")
                    subprocess.run(["pkill", "-f", "langgraph dev"], capture_output=True)
                    time.sleep(2)  # Wait for process to die
                
                # Start new backend process using venv's langgraph
                print("[CONFIG] Starting langgraph dev...")
                working_dir = Path(__file__).parent
                langgraph_path = working_dir / ".venv" / "bin" / "langgraph"
                
                # If langgraph not in venv, try system PATH
                if not langgraph_path.exists():
                    langgraph_path = "langgraph"
                else:
                    langgraph_path = str(langgraph_path)
                
                subprocess.Popen(
                    [langgraph_path, "dev", "--port", "2024"],
                    cwd=working_dir,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    start_new_session=True
                )
                
                # Wait for backend to start (max 30 seconds)
                started = False
                for _ in range(30):
                    time.sleep(1)
                    if is_backend_running():
                        started = True
                        break
                
                if started:
                    action = "restarted" if was_running else "started"
                    print(f"[CONFIG] Backend {action} successfully")
                    self._send_json({
                        "success": True,
                        "message": f"Backend {action} successfully.",
                        "action": action,
                    })
                else:
                    print("[CONFIG] Backend failed to start within timeout")
                    self._send_json({
                        "success": False,
                        "message": "Backend failed to start. Check terminal for errors.",
                        "command": "cd deepagents && langgraph dev --port 2024",
                    })
                    
            except Exception as e:
                print(f"[CONFIG] Error during restart: {e}")
                self._send_json({
                    "success": False,
                    "error": str(e),
                    "message": "Could not start backend. Please start manually.",
                    "command": "cd deepagents && langgraph dev --port 2024",
                })
        else:
            self._send_json({"error": "Not found"}, 404)
    
    def do_DELETE(self):
        """Handle DELETE requests."""
        if self.path == "/config":
            default_config = {
                "provider": "",
                "model": "",
                "api_key": "",
                "base_url": "",
                "model_overrides": {
                    "subagents": {"general-purpose": None},
                    "summarization": None,
                    "suggestions": None,
                },
                "_last_updated": datetime.now().isoformat(),
                "_comment": "Reset to defaults",
            }
            
            try:
                with open(CONFIG_FILE, "w") as f:
                    json.dump(default_config, f, indent=2)
                self._send_json({"success": True, "message": "Config reset to defaults"})
            except Exception as e:
                self._send_json({"error": str(e)}, 500)
        else:
            self._send_json({"error": "Not found"}, 404)
    
    def log_message(self, format, *args):
        """Custom log format."""
        print(f"[CONFIG SERVER] {args[0]}")


def main():
    """Start the config server."""
    print("=" * 60)
    print("Model Config Server")
    print(f"  Port: {PORT}")
    print(f"  Config file: {CONFIG_FILE}")
    print("=" * 60)
    
    server = HTTPServer(("0.0.0.0", PORT), ConfigHandler)
    print(f"Server running on http://127.0.0.1:{PORT}")
    print("Press Ctrl+C to stop")
    
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down...")
        server.shutdown()


if __name__ == "__main__":
    main()
